# Streamlit Cloud Secrets Configuration
# Add your secrets here - these will be encrypted and not visible in your code

# Flask backend URL (if using external backend)
# BACKEND_URL = "https://your-flask-backend.herokuapp.com"

# Database configuration (if using database)
# DATABASE_URL = "postgresql://user:password@host:port/database"

# API Keys (if needed for external services)
# OPENAI_API_KEY = "your-api-key-here"
# AWS_ACCESS_KEY_ID = "your-access-key"
# AWS_SECRET_ACCESS_KEY = "your-secret-key"

# Email configuration (for notifications)
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = 587
# EMAIL_USERNAME = "your-email@gmail.com"
# EMAIL_PASSWORD = "your-app-password"

# File upload settings
MAX_FILE_SIZE_MB = 50
ALLOWED_FILE_TYPES = ["png", "jpg", "jpeg", "tiff", "bmp", "json", "xlsx", "xls"]

# Security settings
SECRET_KEY = "your-secret-key-change-this-in-production"
